### ISSUE TITLE
My tears are visible.

### ISSUE THREAD

**Issue by chadfurman** [utkusen/hidden-tear#1]
This project makes me cry.

**Comment by utkusen** [comment]
you just broke my heart

**Comment by TETYYS** [comment]
this is 2 hours of work, pretty sad

**Comment by utkusen** [comment]
this is 7 years + 2 hours of work

**Comment by chadfurman** [comment]
Yes the work done to prepare you for the 2 hours of work.

Where's the backdoor, plxplx?  :)

**Comment by utkusen** [comment]
i didn't want to make this so advanced in order to don't cause a total mayhem. there is no backdoor. it's just a sample

**Comment by chadfurman** [comment]
@}-,-`-
