### ISSUE TITLE
Weak encryption implementation

### ISSUE THREAD

**Issue by yorickdewid** [utkusen/hidden-tear#10]
Encrypting using the symmetric codeschema is weak since the program is vulnerable to all kinds of injections and attacks. Since the entire encryption occurs on the client side a virusscanner (of sorts) could easily hook in, even after the event.
- The generated password is way too short and can be tried within a reasonable (69^15) amount of time.
- Because you trust on a symmetric codeschema the password must me present somewhere and can (especially with a language like C#) be retrieved quite easily from a memory dump.
- Moving (encrypted) files around only changes the file descriptor towards the modifications, but does not actually alter the entire datablock which makes it easy to recover the original files by walking over the physical pages.
- Since C# relies for the most part on the .NET framework, basically all operations can be monitored or reverted with little effort (opcodes have some degree of transparency).

Randsomeware like CrytoLocker (one of the most successful crytopvirusses we know so far) take on an entire different approach. They trust on asymmetric encryption, specifically RSA, in which the private key never reaches the client system. This is much more secure since it's only the public key that needs to be exchanged between the parties. Also, you should write directly against the system libraries where needed to prevent hooks from listening in on communication. Supply your own crypto functions or use a open library instead. This all usually leads to a language with a lower abstraction level, for example C/C++.

There is the argument of complexity for these measures, but 'keeping things simple' is something you cannot afford in these areas where basically everything revolves around security. As for the education; this could barely pass as an encryption tool, never less malicious software.

**Comment by utkusen** [comment]
Thank you for your comment. But I answered it before here https://github.com/utkusen/hidden-tear/issues/7
