### ISSUE TITLE
Update: Detection Rate 7/35 2015-09-15

### ISSUE THREAD

**Issue by LazerPanther** [utkusen/hidden-tear#19]
**File Name:** hidden-tear.exe
**File Size:** 12 KB
**Scan Date:** 2015-09-15
**Scan Result: 7/35**

**MD5:** 94ce7ab77e933c83410b38e455cd0b91
**Verified By NoDistribute:** [Virus Scan Result](//NoDistribute.com/result/6a4jDwi83Fzt)

AVG Free:Could be a Trojan horse Cryptic
Avast:MSIL:Ransom-J [Trj]
AntiVir (Avira): Clean
BitDefender: Clean
Clam Antivirus: Clean
COMODO Internet Security: Clean
Dr.Web: Clean
eTrust-Vet: Clean
F-PROT Antivirus: Clean
F-Secure Internet Security: Clean
G Data:MSIL.Trojan-Ransom.Cryptear.A
IKARUS Security: Clean
Kaspersky Antivirus:HEUR:Trojan.Win32.Generic
McAfee:Ransomware-FAL!94CE7AB77E93
MS Security Essentials: Clean
ESET NOD32:Trojan.MSIL/Filecoder.Y
Norman: Clean
Norton Antivirus:Trojan.Cryptolocker.Y
Panda Security: Clean
A-Squared: Clean
Quick Heal Antivirus: Clean
Solo Antivirus: Clean
Sophos: Clean
Trend Micro Internet Security: Clean
VBA32 Antivirus: Clean
Zoner AntiVirus: Clean
Ad-Aware: Clean
BullGuard: Clean
FortiClient: Clean
K7 Ultimate: Clean
NANO Antivirus: Clean
Panda CommandLine: Clean
SUPERAntiSpyware: Clean
Twister Antivirus: Clean
VIPRE: Clean

**Comment by utkusen** [comment]
of course it will detect by antivirus programs after a while. but code can be obsfucate to bypass antiviruses

**Comment by LazerPanther** [comment]
I am well aware. Simply mentioning the updated results because you state in the Readme, 
- Undetectable by antivirus programs (15/08/2015) http://nodistribute.com/result/6a4jDwi83Fzt

These are the 1 month later scans.

**Comment by phr34k0** [comment]
Honestly i don't get the idea to hidden-tear. The moment that end user
happeneds to be a power user like most of us and uses linux/unix operating
system, day can null this anyday except when it patches the BIOS to run a
crafted code.

**Comment by phr34k0** [comment]
they*

**Comment by utkusen** [comment]
@LazerPanther actually detection ratio is worse than this one if you put the file on virustotal

@phr34k0 i didn't understand anything

**Comment by phr34k0** [comment]
What i meant was ( Layman terms to non savvy ) hidden-tear is a ransomware
virus that you can create right? Well imagine that target user has a
multibooted computer which can boot both linux and windows.

Given the nature that this hidden-tear.exe only runs on a system level,
user can always boot into linux and delete or even fix their windows
partition by removing those infected files.

Compared that to a rootkit.

**Comment by phr34k0** [comment]
Google BadBios.. With that kind of method, you as the creator can bypass
antivirus anytime without a cryptor

**Comment by utkusen** [comment]
@phr34k0 I think you don't understand the point of ransomware programs. It doesn't harm the system or cause an infection. It just encrypt files. You can't bring back the files without encryption key. Having a multibooted system has no effect on retrieving the encryption key.

**Comment by ivansalomon** [comment]
Hey guys! Don't upload files to virustotal.com. This happens the firm to antivirus companies.
A good site is http://www.refud.me
Good job @utkusen !
