### ISSUE TITLE
How to make it edit multiple subdirectories

### ISSUE THREAD

**Issue by OP737** [utkusen/hidden-tear#23]
Nothing here

**Comment by utkusen** [comment]
it's automatically encrypts all subdirectories under "path" directory

**Comment by OP737** [comment]
I wanted to encrypt all directory under "c:/user/." That is all files under "user" directory. So I changed the line from "\desktop\test"; to "\\".
But when I try to run the program, I get an error stating:

Unhandled exception has occured in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Access to the path 'C:\Users\8WinCon2\AppData\Local\Application Data'is denied.

I have tried to have it bypass AppData folder and encrypt all other folders, but have failed. I have spent the past 2 days and still can't get it to work. 

Please how can I modify the code to encrypt all folders under 'user' sub-directory.

Please help.

**Comment by utkusen** [comment]
hidden tear does not have permission bypass method. I can't help you on that

**Comment by OP737** [comment]
I am not trying to bypass the permission. I just want to add more than 1 path. So instead of only "\desktop\test";  
I would like to add more: "\Documents\test"; 
"\Pictures\";

**Comment by OP737** [comment]
I am not trying to bypass the permission. I just want to add more than 1 path. So instead of only "\desktop\test";

I would like to add more: "\Documents\test";
"\Pictures\";
Please help.

**Comment by OP737** [comment]
utkusen please don't ignore me. Any help will be highly appreciated.

**Comment by OP737** [comment]
utkusen

**Comment by OP737** [comment]
utkusen utkusen

**Comment by OP737** [comment]
Please help me

**Comment by OP737** [comment]
Please Please Please help me. I have already spent two days trying to figure this out.

**Comment by utkusen** [comment]
you can create two startAction() functions to define different paths. And call them in form load section. However I won't help you further, if you have basic programming skills, you can fix that
