### ISSUE TITLE
Multiple folders bug

### ISSUE THREAD

**Issue by Madoff-X** [utkusen/hidden-tear#4]
Just reading the code it appear to me that in case of multiple folders you'll most probably definitely loose the passwords but one. Due to the usage of sendControl variable...

Nice demo though, for wanna-be black/white hats!

**Comment by utkusen** [comment]
thank you for your feedback. i will check that

**Comment by utkusen** [comment]
@Madoff-X yes that was a silly mistake. i fixed the bug i think. can you check? thank you again.

**Comment by Madoff-X** [comment]
QA passed ;-)
