### ISSUE TITLE
Congratz!

### ISSUE THREAD

**Issue by 10urshin** [utkusen/hidden-tear#6]
Just wanted to congratulate you for your file encryption program. I did not understand why you called your file encryption program as ransomware tho.

Also this is just a legit file encryption, if this program without modification, get's caught by any antivirus this is definitely a false/positive.

**Comment by utkusen** [comment]
actually i didn't called it as ransomware. I said it's "ransomware-like" . It can be legit or malicious that depends on user's intention. Just like a knife

**Comment by 10urshin** [comment]
You did called it as "a simple and open source file crypter" tho in your "initial commit" https://github.com/utkusen/hidden-tear/blob/d00cbfec9c5d71c5b085d7661d472bb8844e8e0b/README.md. Which means you already know what this actually is. Was it too uninteresting to call it that? Or did you just wanted to put a fancy headline?? Anyway I already lost my interest, I think that's too much for a "butter knife".
