### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by qgustavor** [utkusen/hidden-tear#7]
If I understood from the readme it simply encrypts the file using AES, which use symmetric keys. Is just that? Real ransomware use asymmetric schemes so even if the connection is MITM-ed (some corporate proxy which logs even HTTPS requests) or in case of reverse engineering isn't possible to decrypt files.

Of course asymmetric cryptography don't work for large files out-of-box, so you either need to encrypt just part of file, sufficient to make it not utilizable anymore (an ransomware like scheme), or encrypt the AES key using an public key generated in the server (an PGP like scheme) but requires more security in order to avoid the AES key be retrieved without the private key.

I don't understand well C#, so I want to know how it works, in specific: it just encrypts with AES or use one of the schemes above?

**Comment by utkusen** [comment]
I explained before why I didn't use asymmetric encryption. I didn't want to make this program so advanced. My point wasn't causing a chaos. It's just a sample which shows that how we can use basic encryption techniques to create a malware.

**Comment by qgustavor** [comment]
Understood. I checked closed issues but those seemed to be only complies, like ["This project makes me cry."](https://github.com/utkusen/hidden-tear/issues/1#issue-101464245). Because this I don't saw the "I explained before".
